# Generated by Django 4.0.3 on 2022-03-01 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataDisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfWorks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicationLimits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UpperHumidityLimit', models.IntegerField()),
                ('UpperTemperatureLimit', models.IntegerField()),
                ('LowerHumidityLimit', models.IntegerField()),
                ('LowerTemperatureLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryOfWorks_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataDisplay.categoryofworks')),
                ('IndicationLimits_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataDisplay.indicationlimits')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodOfTheYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manual_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataDisplay.manual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manual',
            name='PeriodOfTheYear_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataDisplay.periodoftheyear'),
        ),
    ]
