# Generated by Django 4.0.3 on 2022-03-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataDisplay', '0004_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Receiving_time', models.TimeField()),
                ('Receiving_date', models.DateField()),
                ('Humidity', models.FloatField()),
                ('Temperature', models.FloatField()),
                ('Sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataDisplay.sensor')),
            ],
        ),
    ]
