# Generated by Django 4.0.3 on 2022-03-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDisplay', '0006_alter_indications_receiving_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indications',
            name='Receiving_date',
        ),
        migrations.RemoveField(
            model_name='indications',
            name='Receiving_time',
        ),
        migrations.AddField(
            model_name='indications',
            name='Receiving_data_time',
            field=models.DateTimeField(null=True),
        ),
    ]
