# Generated by Django 4.0.3 on 2022-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDisplay', '0007_remove_indications_receiving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indications',
            name='Receiving_data_time',
            field=models.DateTimeField(),
        ),
    ]
