# Generated by Django 4.0.3 on 2022-03-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDisplay', '0009_alter_indications_receiving_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indications',
            name='Receiving_data_time',
            field=models.IntegerField(),
        ),
    ]
