# Generated by Django 4.0.2 on 2022-03-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataDisplay', '0010_alter_indications_receiving_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationsIndications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Indications_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataDisplay.indications')),
            ],
        ),
    ]
